// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiceEEyZPH5KGIUnAy0Zkl9BeID1ts4fY',
    appId: '1:907757118251:web:5e0af769ff18989ee0db6e',
    messagingSenderId: '907757118251',
    projectId: 'selforder-c7da0',
    authDomain: 'selforder-c7da0.firebaseapp.com',
    storageBucket: 'selforder-c7da0.firebasestorage.app',
    measurementId: 'G-Z4DQNY4ZSN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4aHDzXuxpFvaFllqVUYOFC_fWokHRgKE',
    appId: '1:907757118251:android:924986e7e82024a7e0db6e',
    messagingSenderId: '907757118251',
    projectId: 'selforder-c7da0',
    storageBucket: 'selforder-c7da0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmF8ca8C36xy241_KHegGhBeZ3X2fLbCM',
    appId: '1:907757118251:ios:d77d504ef0fcc664e0db6e',
    messagingSenderId: '907757118251',
    projectId: 'selforder-c7da0',
    storageBucket: 'selforder-c7da0.firebasestorage.app',
    iosBundleId: 'com.example.selforder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmF8ca8C36xy241_KHegGhBeZ3X2fLbCM',
    appId: '1:907757118251:ios:d77d504ef0fcc664e0db6e',
    messagingSenderId: '907757118251',
    projectId: 'selforder-c7da0',
    storageBucket: 'selforder-c7da0.firebasestorage.app',
    iosBundleId: 'com.example.selforder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAiceEEyZPH5KGIUnAy0Zkl9BeID1ts4fY',
    appId: '1:907757118251:web:3500dea539f25720e0db6e',
    messagingSenderId: '907757118251',
    projectId: 'selforder-c7da0',
    authDomain: 'selforder-c7da0.firebaseapp.com',
    storageBucket: 'selforder-c7da0.firebasestorage.app',
    measurementId: 'G-T85HRFPT8X',
  );
}
